### ISSUE TITLE
Include guard names collision

### ISSUE THREAD

**Issue by Enhex** [boostorg/spirit#257]
I'm getting this error when trying to use karma in boost 1.65.1:
`'signbit': is not a member of 'boost::spirit::detail'`

It seems that `SPIRIT_SIGN_MAR_11_2009_0734PM` is already defined in:
`boost\spirit\home\x3\support\numeric_utils\sign.hpp`
which triggers the include guard of:
`boost\spirit\home\support\detail\sign.hpp`

I can work around it by using this code:
```C++
namespace boost {
	namespace spirit {
		namespace detail {
			using boost::spirit::x3::signbit;
		}
	}
}
```

**Comment by Kojoley** [comment]
https://svn.boost.org/trac10/ticket/12084 is linked issue
