### ISSUE TITLE
"Phoenix" links are broken in documentation

### ISSUE THREAD

**Issue by octopus-prime** [boostorg/spirit#306]
Starting here
http://www.boost.org/doc/libs/1_65_1/libs/spirit/doc/html/spirit/qi/reference/auxiliary/lazy.html
and clicking the `Phoenix` link you end up with `404`.

The `Phoenix` link is
http://www.boost.org/doc/libs/1_65_1/libs/spirit/phoenix/doc/html/index.html
but should be
http://www.boost.org/doc/libs/1_65_1/libs/phoenix/doc/html/index.html

**Comment by octopus-prime** [comment]
Same problem here
http://www.boost.org/doc/libs/1_65_1/libs/spirit/doc/html/spirit/qi/reference/parser_concepts/nonterminal.html

So probably all "Phoenix" links are broken.

**Comment by djowel** [comment]
Oh no! What could have happened?

**Comment by octopus-prime** [comment]
In `spirit2.qbk` are two definitions:
```
[def __phoenix__                [@../../phoenix/doc/html/index.html Phoenix]]
[def __boost_phoenix__          [@boost:/libs/phoenix/doc/html/index.html Boost.Phoenix]]
```
The latter seams to be correct but the former is used everywhere. E.g.
```
The `lazy` parser, as its name suggests, invokes a lazy __phoenix__
function that returns a parser at parse time. This parser will be
used once it is created to continue the parse.
```
