### ISSUE TITLE
Unsupported compilers

### ISSUE THREAD

**Issue by Kojoley** [boostorg/spirit#332]
Compiler    | Module | Problem
----------- | ----------- | --------
MSVC 7.1 | fusion::fold | [log](http://www.boost.org/development/tests/develop/developer/output/igaztanaga-develop-msvc-7-1-boost-bin-v2-libs-fusion-test-vector_misc-test-msvc-7-1-dbg-dbg-symbl-off-thrdp-wn32-thrd-mlt.html)
clang 3.0 c++11 | fusion::vector | [log](http://www.boost.org/development/tests/develop/developer/output/teeks99-02-dc3-0-11-Docker-64on64-boost-bin-v2-libs-spirit-test-lex-lex_auto_switch_lexerstate-test-clang-gnu-linux-3-0~c++11-debug-threadapi-pthread.html) compiler bug [cwg defect 945](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#945)
clang 3.1 c++11 | spirit::lex | [log](http://www.boost.org/development/tests/develop/developer/output/teeks99-02-dc3-1-11-Docker-64on64-boost-bin-v2-libs-spirit-test-lex-lex_token_omit-test-clang-gnu-linux-3-1~c++11-debug-threadapi-pthread.html)

It is even hard to obtain an environment with these compilers to try to fix the problems.
I going to mark them unusable in `explicit-failures-markup.xml`. Any objections?

P.S.: Is there a planned date for removing Spirit.Classic?

**Comment by djowel** [comment]
No objections here.

Re: PS: The problem is that there are Boost libraries (wave and serialization) that relies on classic.

**Comment by Kojoley** [comment]
Also: Graph uses `classic_multi_pass`. Log and Math uses classic in tests.
And, OMG, [LibreOffice uses classic](https://github.com/LibreOffice/core/search?utf8=%E2%9C%93&q=spirit+classic&type=).

**Comment by djowel** [comment]
LibreOffice! Gee, they should switch to at least Qi.

**Comment by Kojoley** [comment]
> Gee, they should switch to at least Qi.

They have added this note 7 years ago https://github.com/LibreOffice/core/blob/master/filter/source/svg/units.cxx#L92 :laughing:

**Comment by djowel** [comment]
Interesting. That code should be very clean when implemented with Qi or X3.

**Comment by djowel** [comment]
But yeah, there are a LOT of "classic" users:

http://boost-spirit.com/home/info/who-is-using-spirit/

**Comment by Kojoley** [comment]
You can remove Epoch from the list, they replaced Spirit with hand written parser a long time ago AFAIK.

**Comment by Kojoley** [comment]
Update: Added MinGW GCC 4.3 to the list

**Comment by Kojoley** [comment]
Update: Removed Clang 3.0 C++11. Should be fixed as of boostorg/fusion#166.
