### ISSUE TITLE
warning: 'BOOST_ENDIAN_DEFAULT_CONSTRUCT' macro redefined

### ISSUE THREAD

**Issue by redboltz** [boostorg/spirit#348]
When I include both `boost/spirit/include/qi.hpp` and `boost/endian/buffers.hpp`, I got `warning: 'BOOST_ENDIAN_DEFAULT_CONSTRUCT' macro redefined`.

```cpp
#include <boost/spirit/include/qi.hpp>
#include <boost/endian/buffers.hpp>

int main() {
}
```

https://wandbox.org/permlink/lwc8uW2Giwr3CWO7

It seems that the macro should be defined appropriate point, but I'm not sure where is it.

I found the issue Boost 1.66.0 (current release).

**Comment by Kojoley** [comment]
Should be fixed in #349.
