### ISSUE TITLE
X3 Documentation render problems

### ISSUE THREAD

**Issue by Kojoley** [boostorg/spirit#363]
It looks like QuickBook treats commented out links in some special way?

`Compound Parser Attribute Types` [X3](https://www.boost.org/doc/libs/develop/libs/spirit/doc/x3/html/spirit_x3/quick_reference/compound_attribute_rules.html#spirit_x3.quick_reference.compound_attribute_rules.compound_parser_attribute_types) [Qi](http://www.boost.org/doc/libs/develop/libs/spirit/doc/html/spirit/qi/quick_reference/compound_attribute_rules.html#spirit.qi.quick_reference.compound_attribute_rules.compound_parser_attribute_types)

**Comment by Xeverous** [comment]
first link 404

**Comment by Kojoley** [comment]
Yeah, I know, @djowel seems to broken old urls in 54d0167bc8e2253e432158cc863a3803a2af323c.

**Comment by djowel** [comment]
oh!

**Comment by djowel** [comment]
i'm fixing this now

**Comment by djowel** [comment]
should be fixed now (develop)

**Comment by Kojoley** [comment]
I thought it should be fixed in other place... Looks good, thanks!
