### ISSUE TITLE
x3 literal ints

### ISSUE THREAD

**Issue by dvirtz** [boostorg/spirit#390]
It seems that literal int parsers are not implemented yet. 
For example the code
```c++
std::string input = "5";
assert(b::parse(input.begin(), input.end(), b::int_(5)));
assert(b::parse(input.begin(), input.end(), b::lit(5)));
```

does not compile with 
```c++
namespace b = boost::spirit::x3;
```
but does with 
```c++
namespace b = boost::spirit::qi;
```

see https://wandbox.org/permlink/VFrnkOt9sTibHdvA

is there an alternative or plans to support this?

**Comment by dvirtz** [comment]
Thanks. 
My solution is to convert it to a literal string parser using std::to_string:

```c++
int main() {
    std::string input = "5";
    assert(b::parse(input.begin(), input.end(), std::to_string(5)));
}
```

**Comment by djowel** [comment]
X3 is meant to be kept as simple as possible. I'm not sure we need literal ints.
