### ISSUE TITLE
boost/spirit/home/support/detail/lexer/serialise.hpp header

### ISSUE THREAD

**Issue by Kojoley** [boostorg/spirit#433]
There is a strange header [`boost/spirit/home/support/detail/lexer/serialise.hpp`](https://github.com/boostorg/spirit/blob/c87e8772b4223fe0b8e7ed6751d1a91ae65240fe/include/boost/spirit/home/support/detail/lexer/serialise.hpp), it defines a serialization function for lex state machine class, but the header is not used anywhere in Spirit. The location under `detail` folder makes it explicitly prohibited to be used outside of the Spirit itself (but I still searched Boost and Internet and did not find anything). There is unneeded Boost.Serialization include in it that is being found by `boostdep` utility marking Spirit as having a dependency on it (there is even an entry on the Boost wiki about this https://svn.boost.org/trac10/wiki/ModuleDepednecies#Spirit-Serialization), but I cannot even test its removal because there are no tests or usages. All this makes me think that it would be better to remove the header completely.

**Comment by Kojoley** [comment]
However, the commentouted code in Wave examples is not a big reason to maintain the header. What are your suggestions @hkaiser?

**Comment by hkaiser** [comment]
I agree, no need to keep the file.
