### ISSUE TITLE
X3: Sequence in variant parser with container attribute

### ISSUE THREAD

**Issue by Xeverous** [boostorg/spirit#434]
This problem originates from https://stackoverflow.com/questions/48390872 (not my question).

SO attempt: http://coliru.stacked-crooked.com/a/56007d3f997b9748

My attempt: http://coliru.stacked-crooked.com/a/3365b20994ce460e

It seems that `\` is basically impossible to obtain, it's always skipped.

Also, current X3 doc states that the attribute of `lit(c)` is unused and the attribute of `char_(c)` is the type of `c`. This does not seem to be the case as the first code sample has no difference between `lit(c)` and `char_(c)` versions.

**Comment by Kojoley** [comment]
MWE:
```cpp
#include <boost/spirit/home/x3.hpp>
#include <iostream>
#include <string>

namespace x3 = boost::spirit::x3;

int main()
{
    char const* s = "aaabcd", *const end = s + std::strlen(s);
    std::string x;
    if (!parse(s, end, *((x3::char_('a') >> x3::char_) | x3::char_), x))
        std::cout << "failed\n";
    else
        std::cout << "result=" << x << '\n';
}
```
Output:
```
result=abcd
```
https://wandbox.org/permlink/SSv343kksXESwQyU

The fun part is that `&` operator forces it to synthesize the value (while it should not)

```cpp
#include <boost/spirit/home/x3.hpp>
#include <iostream>
#include <string>

namespace x3 = boost::spirit::x3;

int main()
{
    char const* s = "aaabcd", *const end = s + std::strlen(s);
    std::string x;
    if (!parse(s, end, *((&x3::char_('a') >> x3::char_) | x3::char_), x))
        std::cout << "failed\n";
    else
        std::cout << "result=" << x << '\n';
}
```
Output:
```
result=aaabcd
```

@djowel what is the difference between `&a` and `omit[a]`? Ain't they the same thing?

**Comment by Kojoley** [comment]
The actual problem should is sequence in variant parser with container attribute.
The `((x3::char_ >> x3::char_) | x3::char_)` parser does not even compile with container attributes.
With repeated parsers the sequence just returns the last value:
```cpp
#include <boost/spirit/home/x3.hpp>
#include <iostream>
#include <string>

namespace x3 = boost::spirit::x3;

int main()
{
    char const* s = "aaabcde", *const end = s + std::strlen(s);
    std::string x;
    if (!parse(s, end, *((x3::char_ >> x3::char_ >> x3::char_) | x3::char_), x))
        std::cout << "failed\n";
    else
        std::cout << "result=" << x << '\n';
}
```
Output:
```
result=ade
```
https://wandbox.org/permlink/4jdOsdfo5wcRhuXg

**Comment by Kojoley** [comment]
Nevermind, I thought I wrote `&x3::char_('a') >> x3::char_ >> x3::char_) | x3::char_`.

**Comment by Kojoley** [comment]
After #439 the examples above instead of compiling and silently doing something wrong will fire a static assert (the assert is for the user ill-formed code, but it founds a bug in Spirit so it is not that informative). They also perform backtracking and need explicit attribute recovery (see #378). For the both issues there is a workaround (and also a speedup hack) if the parser does not skip/dismiss an input - use `raw` directive.

I also see that this and #394 are subsets of a general bug. I have some thoughts on it, but have some more urgent things to do.
