### ISSUE TITLE
Is x3/support/utility/testing.hpp really need to be a public interface?

### ISSUE THREAD

**Issue by Kojoley** [boostorg/spirit#477]
It was added in a3d667002f125aae1482bb2a631475f716d723cb and still only used by a single example. It also includes Boost.Filesystem and Boost.Regex libraries what is not fine as any inclusion makes BCP and Boostdep think the whole library depends on them (there are few other questionable places where this happens).

A bit off-topic, but it also seems to have bugs (see #476) and I do not want to cover it with tests.

**Comment by djowel** [comment]
It does not need to be public.

**Comment by Kojoley** [comment]
Then what was the purpose of a3d667002f125aae1482bb2a631475f716d723cb commit?

**Comment by djowel** [comment]
I think a3d6670 commit is wrong, in retrospect. You are correct that it unnecessarily includes dependencies that we do not want.

**Comment by Kojoley** [comment]
Ok. I will move it back after 1.70 released as technically it is a breaking change and Boost is currently closed for breaking changes.

Please, look at #476, the rexpr example runs fine with it but I may miss something.
