### ISSUE TITLE
`using namespace boost::spirit::endian;` into `boost::endian` causes ambiguity errors

### ISSUE THREAD

**Issue by pdimov** [boostorg/spirit#481]
The using directive in

https://github.com/boostorg/spirit/blob/5a80befedd5f9821d0d0ea890a7edd6d84d5a561/include/boost/spirit/home/support/detail/endian/endian.hpp#L560-L563

causes ambiguity errors when using Spirit and Endian together. A library is not supposed to inject things into another library's namespace. Please fix this.

**Comment by Kojoley** [comment]
I noticed it recently that Spirit injects into endian namespace, but as you may know, this was living before Endian appeared. I would like to drop internal endian stuff completely, but Endian does not support floats and from the docs it looks like Endian does not want to support floats either. Moreover it does not case ambiguity errors for me, I tried with:

```cpp
#include <boost/spirit/home/support/detail/endian/endian.hpp>
#include <boost/endian/conversion.hpp>
#include <boost/endian/arithmetic.hpp>
int main(){}
```

**Comment by djowel** [comment]
> I noticed it recently that Spirit injects into endian namespace, but as you may know, this was living before Endian appeared. 

I did not know about this. Do you know when this happened?

**Comment by Kojoley** [comment]
> Do you know when this happened?

From the very beginning, in 0d75b4307afa27724e794dd29f503e219bb6805f

**Comment by djowel** [comment]
OK, thoughts, @hkaiser ?

**Comment by pdimov** [comment]
I'm not saying that you need to drop anything. Just don't mess with `namespace boost::endian`.

**Comment by Kojoley** [comment]
> I'm not saying that you need to drop anything. Just don't mess with `namespace boost::endian`.

And I am not saying this should stay, what I am trying to tell you that it had not been there for a long time already if Endian supported floats. IIUC that is the reason it outlived adding the Endian library.

**Comment by pdimov** [comment]
The ambiguity was reported in https://github.com/boostorg/endian/issues/33.

Re floats, the Endian library is probably due to an internal rewrite, I don't know when I'll find the time to get to it. Periodical reminders might help. :-)

(Its whole underlying idea - that a `T`, with endianness reversed, can still be stored as `T` and passed and returned by value, is flawed.)

**Comment by Kojoley** [comment]
> Re floats, the Endian library is probably due to an internal rewrite, I don't know when I'll find the time to get to it. Periodical reminders might help. :-)

I have https://github.com/Kojoley/endian/commit/c0c204f06ebf3c3bcc67d1b39aad552ab40c6a8c in my stash, if you ok with the general idea I can prepare a PR.

> (Its whole underlying idea - that a `T`, with endianness reversed, can still be stored as `T` and passed and returned by value, is flawed.)

Unaligned Endian types store the value as array of chars and does type punning on store/load. Aligned ones could make the same with C++11 `alignas`, and on C++03 store as unsigned integers as long as there is unsigned integer type with the requested size and it does not have a trap representation.

**Comment by pdimov** [comment]
I need more context to evaluate this patch - what code doesn't work before it and works after it?

**Comment by Kojoley** [comment]
> I need more context to evaluate this patch - what code doesn't work before it and works after it?

```cpp
#include <boost/endian/arithmetic.hpp>

int main()
{
    boost::endian::endian_arithmetic<boost::endian::order::big, float, sizeof(float) * 8> a;
    a = 123.4f;
    float b = a;
    return b == 123.4f ? 0 : 1;
}
```

PS: I tried to rebase the patch on top of the current develop and it is no longer works =\

**Comment by pdimov** [comment]
I rewrote load/store and now the above float example works, but the test using

```
  class MyInt
  {
    int32_t mx;
  public:
    MyInt(int32_t x = 0) : mx(x) {}
    operator int32_t() const {return mx;}

    //friend int32_t operator+(const MyInt& x) {return x;}
  };
```

now fails, because MyInt isn't trivial and g++ 8 warns on memcpy-ing it. :-/

**Comment by Kojoley** [comment]
It is ok, is not it?

PS: I rebased the patch https://github.com/Kojoley/endian/commit/9becd36acfa67de2ef4d07444f58827c4e5045f0

**Comment by pdimov** [comment]
The Endian library (on develop) now supports `float` and `double`.

**Comment by Kojoley** [comment]
> The Endian library (on develop) now supports `float` and `double`.

That's awesome, thanks!

**Comment by djowel** [comment]
Great! Thanks,  Peter!
