### ISSUE TITLE
X3: missing long double parser

### ISSUE THREAD

**Issue by Xeverous** [boostorg/spirit#500]
https://github.com/boostorg/spirit/blob/8d5429ad7b69a6a1b479f4216ef200a368472de2/include/boost/spirit/home/x3/numeric/real.hpp#L54-L58

There is no `long_double` parser as mentioned by documentation

https://www.boost.org/doc/libs/1_70_0/libs/spirit/doc/x3/html/spirit_x3/quick_reference/numeric.html

**Comment by Kojoley** [comment]
Do you need that parser or you just pointing to the documentation problem?

**Comment by Xeverous** [comment]
I don't need the parser (even if did, I could just write `real_parser<long double>`). Just pointing out mismatch between documentation and implementation.

**Comment by djowel** [comment]
I'll add this. Thanks for noting!

**Comment by djowel** [comment]
Done. Added some tests as well and along with it some tweaks to take advantage of constexpr in the pow10 tables.
