### ISSUE TITLE
Memcpy compilation error in utree_detail2.hpp

### ISSUE THREAD

**Issue by janos-varga** [boostorg/spirit#502]
Hi Boost Community,
Consider the following Hello World program, hello.cpp:
```
#include <boost/spirit/include/support_utree.hpp>
#include <iostream>
using namespace std;
int main() {
    cout << "Hello, World!";
    return 0;
}
```
When compiling this, g++ hello.cpp -o hello, we get the following compilation error (excerpt):
```
utree_detail2.hpp:48:14: error: 'memcpy' is not a member of 'std'
         std::memcpy(&tmp, &buff[small_string_size-2], sizeof(tmp));
              ^~~~~~
```
I propose a fix:
include cstring and add using namespace std; just like in lexer/file_input.hpp or lexer/parser/tokeniser/re_tokeniser.hpp.

**Comment by Kojoley** [comment]
1) Does including `<cstring>` before utree solves the problem?
2) What are you compiler and standard library versions?

> add using namespace std;

This is not required. It was a workaround for old standard library implementations IIRC.

**Comment by janos-varga** [comment]
1. Yes.
2. My GCC and stdlib are version 8.3.0.
