### ISSUE TITLE
attribute of x3::raw

### ISSUE THREAD

**Issue by wanghan02** [boostorg/spirit#509]
`x3::raw` has a placeholder attribute type `raw_attribute_type`. I think it's because we don't know the `Iterator` type yet before calling `parse` function. Then we have some tricks to replace this placeholder type in semantic action if it is attached directly to `x3::raw`. It even works if `x3::raw` is the only parser with attribute in a sequence of parsers. However, it doesn't work for more complex parsers say a sequence of `x3::raw`, or alternative parser with `x3::raw` as one of the branches. 

We find `x3::raw` very useful because we avoid creating unnecessary containers as much as possible and use range instead. For the complex parsers using `x3::raw` we have to workaround this problem by defining a rule with attribute for it, which is not very elegant (something like `qi::as`, but still). 

Can we solve this problem by dumping this placeholder attribute type? Say by adding a template parameter `Iterator` to `attribute_of` and specialize `attribute_of` for `x3::raw`. This placeholder attribute type already brought some customization points and it is far from enough.

**Comment by djowel** [comment]
Could you please post some code that exhibits this behavior?

**Comment by wanghan02** [comment]
@djowel Sure! For example this alternative parser. We can not natually synthesize an attribute of `variant<int, boost::iterator_range<It>>` from it. 

```
    std::string str("test");
    x3::parse(
        str.begin(), str.end(), 
        (x3::int_ | x3::raw[*x3::char_])[([](auto const& ctx){
            boost::apply_visitor(
                [](auto const& v) { std::cout<<v<<std::endl; },
                x3::_attr(ctx)
            );
        })]
    );
```

**Comment by djowel** [comment]
I suppose you have the complete minimal cpp file (MCVE)?

**Comment by djowel** [comment]
At any rate, I am not sure what the intent here is. Do you want to capture each char or the full alternatives? Basically, you attach raw and the SA to the node you need. E.g.:

x3::int_ | x3::raw[*x3::char_][semantic_action] // capture the char

or:

x3::raw[x3::int_ | *x3::char_][semantic_action] // capture the alternatives

**Comment by wanghan02** [comment]
The code could be found here [coliru](https://coliru.stacked-crooked.com/a/35a96ea602605853).

**Comment by wanghan02** [comment]
@djowel I think neither of the 2 solutions are good enough. 

Solution#1 of course solves the problem. Actually it solves all the problems but not elegantly. This is why we have attribute type for alternative operator. We want to record this alternative information for later use. The alternative attribute works for all the other parsers but not the raw parser. 

Solution#2 in my opinion does not solve the problem. If we want to use this result later we have to parse it again if it is an int or a string. 

It's not just the alternative operator. A sequence of raw also cannot synthesize an attribute for example.

**Comment by wanghan02** [comment]
The information is **int or string**. Say we have something like this

`(int_ | raw[+char_]) >> some_following_parsers`

We want to use the variant (int or string) only at the end of the whole parser. If we have int, do something. If we have string, do something else. Having a variant attribute is useful in this case. 

It's not about this special case. As I said, alternative operator could synthesize an attribute for any other parsers except raw parser. And sequence operator could also synthesize an attribute for any other parsers with the same attribute except raw parser. My intent is to make raw parser as handy as all the other parsers.

**Comment by djowel** [comment]
OK, I think I understand what you mean now.

**Comment by djowel** [comment]
OK, I have a fix in develop with a test case:

```c++
    {
        using range = boost::iterator_range<std::string::const_iterator>;
        boost::variant<int, range> attr;

        std::string str("test");
        parse(str.begin(), str.end(),  (int_ | raw[*char_]), attr);

        auto rng = boost::get<range>(attr);
        BOOST_TEST(std::string(rng.begin(), rng.end()) == "test");
    }
```
There's a new trait for converting pseudo attributes to the correct type. I recall wanting to do this a long time ago. Now's the chance. I'm sure there are other places that this trait needs to be applied. I'd appreciate your help in providing more test cases. I'll keep this "issue" open.

**Comment by djowel** [comment]
I have more fixes for sequences + tests:

```c++
    {
        std::vector<boost::iterator_range<std::string::iterator>> attr;
        std::string str("123abcd");
        parse(str.begin(), str.end()
          , (raw[int_] >> raw[*char_])
          , attr
        );
        BOOST_TEST(attr.size() == 2);
        BOOST_TEST(std::string(attr[0].begin(), attr[0].end()) == "123");
        BOOST_TEST(std::string(attr[1].begin(), attr[1].end()) == "abcd");
    }

    {
        std::pair<int, boost::iterator_range<std::string::iterator>> attr;
        std::string str("123abcd");
        parse(str.begin(), str.end()
          , (int_ >> raw[*char_])
          , attr
        );
        BOOST_TEST(attr.first == 123);
        BOOST_TEST(std::string(attr.second.begin(), attr.second.end()) == "abcd");
    }
```
