### ISSUE TITLE
How to match the same char?

### ISSUE THREAD

**Issue by w4454962** [boostorg/spirit#518]
one = ch_p("1") | ch_p("2")  | ch_p("3") ;

two = one >> one;    = 12 13 21 23 31 32 
How can I  match 11 22 33 ? Only to match the same characters

**Comment by w4454962** [comment]
one = ch_p("1") || ch_p("2") || ch_p("3") ;
two = repeat_p(2)[one]; 
This solved the

**Comment by w4454962** [comment]
but， How can I match 1 2 3 4 Incremental digital characters

**Comment by djowel** [comment]
This is not really an "issue" is it? Anyway, you can do it using syntactic predicates (e.g. [using eps](https://www.boost.org/doc/libs/1_54_0/libs/spirit/doc/html/spirit/qi/reference/auxiliary/eps.html)) or semantic actions that can "fail" the ongoing parse.
