### ISSUE TITLE
karma::real_policies<double>::fraction_part() formats incorrectly for precision >= 16 for fractions whose digits form an integer >= 999999999999998

### ISSUE THREAD

**Issue by jvanvuren-tableau** [boostorg/spirit#529]
For the current version of Boost, the Karma reals formatting library uses the following code from karma::real_policies<double>::fraction_part():

        static bool fraction_part (OutputIterator& sink, T n
          , unsigned precision_, unsigned precision)
        {
            ...
            typename remove_const<T>::type digits = 
                (traits::test_zero(n) ? 0 : floor(log10(n))) + 1;
            ...

When the precision is >= 16, and "n" (the fractional part of the number converted to an integer) is >= 999999999999998, the expression floor(log10(n))+1 is returning a number of digits required to represent "n" that is 1 too large. When this happens, the final formatted double is 10 times the correct value.

17 digits of precision is the max supported by doubles (https://en.wikipedia.org/wiki/Double-precision_floating-point_format), so it is likely that clients of the Karma library will try to configure it to use that precision, fufilling one of the preconditions for this issue to occur.

Sample code:
```
#include <iostream>

#include <boost/spirit/include/karma.hpp>

namespace karma = boost::spirit::karma;

struct double_policy : karma::real_policies<double> {

    unsigned int precision(double n) const {
        return 16;
    }
};

int main() {

    typedef karma::real_generator<double, double_policy> double_generator;
    const double_generator double_gen = double_generator();

    double x = 0.0999999999999998;
    std::string generated;
    std::back_insert_iterator<std::string> sink(generated);
    karma::generate(sink, double_gen, x);

    std::cout << generated << std::endl;

    return 0;
}
```
Output:
0.999999999999998

**Comment by hkaiser** [comment]
@jvanvuren-tableau Thanks! This looks like a viable solution for larger `n`. Would you have an idea what this `n` could be? Also, would you mind creating a PR for this. I'd gladly accept it.

**Comment by jvanvuren-tableau** [comment]
I've been doing some more reading. The double standard actually only supports 15.9 digits of precision - see https://en.wikipedia.org/wiki/Floating-point_arithmetic. Therefore for someone to try to use karma for format a double with a precision >= 16 digits is invalid. Which would mean that this issue which I submitted is actually invalid :)

**Comment by hkaiser** [comment]
Ok, that's what I was thinking... Are you ok with closing the issue?

**Comment by jvanvuren-tableau** [comment]
Yes - closing issue.

**Comment by jvanvuren-tableau** [comment]
Just a cautionary note - the situation where the log10() call in karma::real_policies<double>::fraction_part() returns a number one too large actually does happen when karma is configured for 15 digits of precision and the input "n" (the digits of the fractional part of the number converted to an integer, stored in a double) is 999999999999998 or larger. But because there are no leading zeroes to be inserted, this issue does not cause the function to incorrectly format the fractional part of the number.

**Comment by hkaiser** [comment]
@jvanvuren-tableau Thanks for this clarification!
