### ISSUE TITLE
#pragma warning (push) / #pragma warning (pop) mismatch in escape_char.ipp when compiling with Visual Studio 2017

### ISSUE THREAD

**Issue by stefan301** [boostorg/spirit#532]
In escape_char.ipp (Boost 1.71.0) there is the following block starting at line 36 enabled when compiling with any Visual Studio release:

#if defined(BOOST_MSVC)
#pragma warning(push)
#pragma warning(disable:4127)
#endif

but the block containing the pop starting at line 169 is only enable when compiling with Visual Studio .NET 2003 (7,1) or older:

#if (defined(BOOST_MSVC) && (BOOST_MSVC <= 1310))
#pragma warning(pop)
#endif

**Comment by djowel** [comment]
Thanks for noting. Could you do a PR for this?
