### ISSUE TITLE
Regression since BOOST 1_70

### ISSUE THREAD

**Issue by artemp** [boostorg/spirit#548]
Minimal use-case : https://github.com/artemp/spirit-x3-test ( somewhat related to #511) 
This code compiles, links and runs as expected with BOOST <= 1.69 (both GCC and clang)  but results in linker error with BOOST >=1.70. Key features are separate TUs for grammar instantiations and use of semantic actions in aggregate grammar. 

/cc @djowel @Kojoley

**Comment by Kojoley** [comment]
I can confirm the bug, regressed with #457, should be fixed with #549.

You can avoid the bug by defining rules with `force_attribute = true` though.

**Comment by artemp** [comment]
@Kojoley - thanks the quick fix!
