### ISSUE TITLE
is_char wont work for sign defined character types

### ISSUE THREAD

**Issue by rezaebrh** [boostorg/spirit#559]
`is_char<char>::value` is true
`is_char<unsigned char>::value` is false
`is_char<signed char>::value` is even false
and
`is_char<typename std::make_signed<unsigned char>::type>::value` is also false

I need to discriminate character types from other  integral types. What should I do?

**Comment by djowel** [comment]
Why exactly do you want to discriminate character types? Do you have a use-case on how it affects spirit? Spirit's is_char only supports char and wchar_t. If you can show a use-case where this is problematic, then we can probably add more. Otherwise, you should just probably make your own traits for that.

**Comment by Kojoley** [comment]
What are you actually trying to achieve? The trait is not meant to be used by users. Its main purpose is a customization point for a case when you are not satisfied with defaults ([read the documentation](https://www.boost.org/doc/libs/1_71_0/libs/spirit/doc/html/spirit/advanced/customize.html)). IIUC, the `is_char` is responsible for enabling literal character/string parser creation/conversion from a literal char/string (like `lit('a')`/`lit("a")`).

**Comment by djowel** [comment]
> IIUC, the `is_char` is responsible for enabling literal character/string parser creation/conversion from a literal char/string (like `lit('a')`/`lit("a")`).

That is correct.

**Comment by rezaebrh** [comment]
> Why exactly do you want to discriminate character types? Do you have a use-case on how it affects spirit? Spirit's is_char only supports char and wchar_t. If you can show a use-case where this is problematic, then we can probably add more. Otherwise, you should just probably make your own traits for that.

It's not like I'm
