### ISSUE TITLE
build only testcases fail because of generated header dependency

### ISSUE THREAD

**Issue by calvincramer** [boostorg/spirit#672]
The regression_matlib_static and regression_matlib_switch testcases are dependent on header files generated by the regression_matlib_generate and regression_matlib_generate_switch testscases respectively. This leads to a compile error when building the tests without running:
```
cd libs/spirit
../../b2 test -j12 -a -d1 testing.execute=off
```
Where the error will be something like:
`../libs/spirit/test/lex/regression_matlib_static.cpp:15:10: fatal error: 'matlib_static.h' file not found`

https://github.com/boostorg/spirit/blob/e30073e5bebb8102c73d1ad3588bf3f68cec2b64/test/lex/Jamfile#L90

This issue was found when running these tests for VxWorks, since tests are built on a host machine and then executables are transferred to VxWorks to test.

**Comment by Kojoley** [comment]
Yes, but how this is a Spirit issue? I am honestly have no idea on what I can do to help you.

**Comment by calvincramer** [comment]
Separate build / execute steps is a common feature from b2 that applies to all boost libraries. The use of dependent test cases breaks that. Spirit should be able to build all tests without running any of these tests.

**Comment by Kojoley** [comment]
I am not sure you are understanding what is going on in these tests. They test lexer 'source' code generators and the generated content too (build source, run to generate source, build and run that). I have no idea how it could be done in your setup, I am pretty sure your solution is by no means a huger hack than these tests.

**Comment by Kojoley** [comment]
> tests are built on a host machine and then executables are transferred to VxWorks to test.

I remember there were [CrystaX Android NDK](https://www.crystax.net/android/ndk) regression bots doing that, maybe try contacting them.

**Comment by calvincramer** [comment]
Thanks @Kojoley for the explanation. I'll reach out to them.
