### ISSUE TITLE
Compilation error in 1.77

### ISSUE THREAD

**Issue by syyyr** [boostorg/spirit#701]
Hi, since Boost 1.77, I am not able to compile my project that uses Spirit X3. I read in the changelog, that there were some breaking changes, but I'm not sure if that's what's affecting me. To be honest, I am kinda lost in the error message. I am not sure what it means. This is the compilation error https://gist.github.com/syyyr/3ee4bac793a0724b4976138ec35f42ed. My grammars can be seen here https://github.com/CESNET/netconf-cli/blob/master/src/grammars.hpp, the AST is in the other files next to this one, but I think that https://github.com/CESNET/netconf-cli/blob/master/src/ast_path.hpp is where the problem might be. Could you please help me solve this issue?

**Comment by Kojoley** [comment]
@syyyr `PathParser` https://github.com/CESNET/netconf-cli/blob/2e092b324796bd869e3f5375c09656b0897786ae/src/path_parser.hpp#L267-L268 must have `static bool const has_attribute = true;`. After this fix you could replace https://github.com/CESNET/netconf-cli/blob/2e092b324796bd869e3f5375c09656b0897786ae/src/path_parser.hpp#L341
```cpp
auto const anyPath = x3::rule<class anyPath_class, AnyPath>{"anyPath"} = PathParser<PathParserMode::AnyPath, CompletionMode::Schema>{};
```
with
```cpp
const PathParser<PathParserMode::AnyPath, CompletionMode::Schema> anyPath{};
```
and that hopefully will workaround the issue.
