### ISSUE TITLE
Spirit test drivers have extraneous ';' when using BOOST_DELETED_FUNCTION

### ISSUE THREAD

**Issue by mclow** [boostorg/spirit#725]
libs/spirit/test/lex/dedent_handling_phoenix.cpp:78:     BOOST_DELETED_FUNCTION(dumper& operator= (dumper const&));
libs/spirit/test/lex/matlib.h:40:     BOOST_DELETED_FUNCTION(store_double& operator= (store_double const&));
libs/spirit/test/lex/matlib.h:61:     BOOST_DELETED_FUNCTION(add_row& operator= (add_row const&));
libs/spirit/test/lex/set_token_value.cpp:83:     BOOST_DELETED_FUNCTION(handle_whitespace& operator= (handle_whitespace const&));
libs/spirit/test/qi/terminal_ex.cpp:72:         BOOST_DELETED_FUNCTION(ops_1_parser& operator= (ops_1_parser const&));
libs/spirit/test/qi/terminal_ex.cpp:124:         BOOST_DELETED_FUNCTION(ops_2_parser& operator= (ops_2_parser const&));
libs/spirit/test/qi/terminal_ex.cpp:181:         BOOST_DELETED_FUNCTION(ops_3_parser& operator= (ops_3_parser const&));

See https://github.com/boostorg/iostreams/issues/147 for a similar report against iostreams.

**Comment by djowel** [comment]
Would you care to do a PR?

**Comment by mclow** [comment]
I could do a PR, but the fix is just to remove the trailing ';' from each of those lines.  Your call.

**Comment by djowel** [comment]
I'll do it. Thanks, Marshall!
